// Package netconf handles reading and writing network configuration files
// (.conf) that store all parameters needed to join a network and start the
// daemon.  The file format is a simple KEY=VALUE per line (shell-compatible).
package netconf

import (
	"bufio"
	"fmt"
	"os"
	"strconv"
	"strings"
)

// NetConf holds all parameters that fully describe how to connect to a network.
type NetConf struct {
	// Required
	NetworkPubKey string `key:"NETWORK_PUB"`

	// Optional – only present on authority nodes
	NetworkPrivKey string `key:"NETWORK_PRIV"`

	// Network parameters
	CIDR           string `key:"CIDR"`
	PreferredIP    string `key:"PREFERRED_IP"`
	HostLocked     bool   `key:"HOST_LOCKED"`
	ListenPort     int    `key:"LISTEN_PORT"`
	BootstrapPeers string `key:"BOOTSTRAP_PEERS"` // comma-separated multiaddrs

	// Daemon parameters
	Verbose  bool   `key:"VERBOSE"`
	StateDir string `key:"STATE_DIR"`
	Socket   string `key:"SOCKET"`
}

// Save writes the config to the given path in KEY=VALUE format.
func (nc *NetConf) Save(path string) error {
	f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0600)
	if err != nil {
		return fmt.Errorf("creating config file: %w", err)
	}
	defer f.Close()

	w := bufio.NewWriter(f)

	writeLine := func(key, val string) {
		if val != "" {
			fmt.Fprintf(w, "%s=%s\n", key, val)
		}
	}

	fmt.Fprintln(w, "# p2pvpn network configuration")
	fmt.Fprintln(w, "# Generated by: p2pvpn network create")
	fmt.Fprintln(w, "")

	writeLine("NETWORK_PUB", nc.NetworkPubKey)
	writeLine("NETWORK_PRIV", nc.NetworkPrivKey)
	fmt.Fprintln(w, "")

	writeLine("CIDR", nc.CIDR)
	writeLine("PREFERRED_IP", nc.PreferredIP)
	if nc.HostLocked {
		writeLine("HOST_LOCKED", "true")
	}
	if nc.ListenPort != 0 {
		writeLine("LISTEN_PORT", strconv.Itoa(nc.ListenPort))
	}
	writeLine("BOOTSTRAP_PEERS", nc.BootstrapPeers)
	fmt.Fprintln(w, "")

	if nc.Verbose {
		writeLine("VERBOSE", "true")
	}
	writeLine("STATE_DIR", nc.StateDir)
	writeLine("SOCKET", nc.Socket)

	return w.Flush()
}

// Load reads a config file from the given path.
func Load(path string) (*NetConf, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening config file: %w", err)
	}
	defer f.Close()

	nc := &NetConf{}
	scanner := bufio.NewScanner(f)
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(scanner.Text())

		// Skip empty lines and comments.
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			return nil, fmt.Errorf("line %d: invalid format (expected KEY=VALUE): %q", lineNo, line)
		}
		key := strings.TrimSpace(parts[0])
		val := strings.TrimSpace(parts[1])

		switch key {
		case "NETWORK_PUB":
			nc.NetworkPubKey = val
		case "NETWORK_PRIV":
			nc.NetworkPrivKey = val
		case "CIDR":
			nc.CIDR = val
		case "PREFERRED_IP":
			nc.PreferredIP = val
		case "HOST_LOCKED":
			nc.HostLocked = parseBool(val)
		case "LISTEN_PORT":
			nc.ListenPort, _ = strconv.Atoi(val)
		case "BOOTSTRAP_PEERS":
			nc.BootstrapPeers = val
		case "VERBOSE":
			nc.Verbose = parseBool(val)
		case "STATE_DIR":
			nc.StateDir = val
		case "SOCKET":
			nc.Socket = val
		default:
			// Ignore unknown keys for forward compatibility.
		}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("reading config file: %w", err)
	}

	if nc.NetworkPubKey == "" {
		return nil, fmt.Errorf("config file %s: NETWORK_PUB is required", path)
	}

	return nc, nil
}

// BootstrapPeerList returns the bootstrap peers as a string slice.
func (nc *NetConf) BootstrapPeerList() []string {
	if nc.BootstrapPeers == "" {
		return nil
	}
	parts := strings.Split(nc.BootstrapPeers, ",")
	var out []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

func parseBool(s string) bool {
	s = strings.ToLower(s)
	return s == "true" || s == "1" || s == "yes"
}
